# Docker Compose file version
version: "3"

# Define services
services:
  # MariaDB service
  db:
    # Use the specified Docker image
    image: mariadb:10.6.5
    # Map host port to container port
    ports:
      - "3306:3306"
    # Set environment variables for MariaDB
    environment:
      MARIADB_USER: "passwordpusher_user"
      MARIADB_PASSWORD: "passwordpusher_passwd"
      MARIADB_DATABASE: "passwordpusher_db"
      # Generate a random root password on startup
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    # Mount host directory to container directory for persistent storage
    volumes:
      - /DATA/AppData/pwpush/mariadb/data:/var/lib/mysql

  # PasswordPusher service
  pwpush:
    # Use the specified Docker image
    image: docker.io/pglombardo/pwpush-mysql:release
    # Map host port to container port
    ports:
      - "5100:5100"
    # Ensure db service is started before pwpush
    depends_on:
      - db
    # Link pwpush to the db service and alias it as mysql
    links:
      - db:mysql
    # Mount host directory to container directory for persistent storage
    volumes:
      - /DATA/AppData/pwpush/storage:/opt/PasswordPusher/storage:rw
