name: Renovate AutoMerge

on:
  pull_request:

jobs:
  automerge:
    if: contains(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Analyze PR for Major Version Bump
        id: analyze
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const description = context.payload.pull_request.body;
            const majorRegex = /\b(major)\b/i; // Regular expression to find "major" in the PR description
            if (majorRegex.test(description)) {
              console.log("Found a major version bump.");
              core.setOutput("automerge", "false");
            } else {
              console.log("No major version bump found.");
              core.setOutput("automerge", "true");
            }

      - name: Add automerge label
        if: steps.analyze.outputs.automerge == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              labels: ['automerge']
            })
